/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as SellSettingsRouteImport } from './routes/sell.settings'
import { Route as SellPromotionsRouteImport } from './routes/sell.promotions'
import { Route as SellProfileRouteImport } from './routes/sell.profile'
import { Route as SellOrdersRouteImport } from './routes/sell.orders'
import { Route as SellAssistantRouteImport } from './routes/sell.assistant'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountReferralsRouteImport } from './routes/account.referrals'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as SellProductsIndexRouteImport } from './routes/sell.products.index'
import { Route as SellProductsNewRouteImport } from './routes/sell.products.new'
import { Route as SellProductsImportRouteImport } from './routes/sell.products.import'
import { Route as SellProductsIdRouteImport } from './routes/sell.products.$id'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellSettingsRoute = SellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellRoute,
} as any)
const SellPromotionsRoute = SellPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SellRoute,
} as any)
const SellProfileRoute = SellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SellRoute,
} as any)
const SellOrdersRoute = SellOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellRoute,
} as any)
const SellAssistantRoute = SellAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => SellRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReferralsRoute = AccountReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const SellProductsIndexRoute = SellProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SellRoute,
} as any)
const SellProductsNewRoute = SellProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => SellRoute,
} as any)
const SellProductsImportRoute = SellProductsImportRouteImport.update({
  id: '/products/import',
  path: '/products/import',
  getParentRoute: () => SellRoute,
} as any)
const SellProductsIdRoute = SellProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => SellRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell': typeof SellRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/referrals': typeof AccountReferralsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sell/assistant': typeof SellAssistantRoute
  '/sell/orders': typeof SellOrdersRoute
  '/sell/profile': typeof SellProfileRoute
  '/sell/promotions': typeof SellPromotionsRoute
  '/sell/settings': typeof SellSettingsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/sell/': typeof SellIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/sell/products/$id': typeof SellProductsIdRoute
  '/sell/products/import': typeof SellProductsImportRoute
  '/sell/products/new': typeof SellProductsNewRoute
  '/sell/products/': typeof SellProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/referrals': typeof AccountReferralsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sell/assistant': typeof SellAssistantRoute
  '/sell/orders': typeof SellOrdersRoute
  '/sell/profile': typeof SellProfileRoute
  '/sell/promotions': typeof SellPromotionsRoute
  '/sell/settings': typeof SellSettingsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/sell': typeof SellIndexRoute
  '/shop': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/sell/products/$id': typeof SellProductsIdRoute
  '/sell/products/import': typeof SellProductsImportRoute
  '/sell/products/new': typeof SellProductsNewRoute
  '/sell/products': typeof SellProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell': typeof SellRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/referrals': typeof AccountReferralsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sell/assistant': typeof SellAssistantRoute
  '/sell/orders': typeof SellOrdersRoute
  '/sell/profile': typeof SellProfileRoute
  '/sell/promotions': typeof SellPromotionsRoute
  '/sell/settings': typeof SellSettingsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/sell/': typeof SellIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/sell/products/$id': typeof SellProductsIdRoute
  '/sell/products/import': typeof SellProductsImportRoute
  '/sell/products/new': typeof SellProductsNewRoute
  '/sell/products/': typeof SellProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/assistant'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/llms.txt'
    | '/login'
    | '/messages'
    | '/robots.txt'
    | '/sell'
    | '/signup'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/referrals'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/stores'
    | '/admin/users'
    | '/blog/$slug'
    | '/sell/assistant'
    | '/sell/orders'
    | '/sell/profile'
    | '/sell/promotions'
    | '/sell/settings'
    | '/shop/$slug'
    | '/store/$slug'
    | '/account/'
    | '/admin/'
    | '/sell/'
    | '/shop/'
    | '/account/orders/$id'
    | '/sell/products/$id'
    | '/sell/products/import'
    | '/sell/products/new'
    | '/sell/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/llms.txt'
    | '/login'
    | '/messages'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/referrals'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/stores'
    | '/admin/users'
    | '/blog/$slug'
    | '/sell/assistant'
    | '/sell/orders'
    | '/sell/profile'
    | '/sell/promotions'
    | '/sell/settings'
    | '/shop/$slug'
    | '/store/$slug'
    | '/account'
    | '/admin'
    | '/sell'
    | '/shop'
    | '/account/orders/$id'
    | '/sell/products/$id'
    | '/sell/products/import'
    | '/sell/products/new'
    | '/sell/products'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/assistant'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/llms.txt'
    | '/login'
    | '/messages'
    | '/robots.txt'
    | '/sell'
    | '/signup'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/referrals'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/stores'
    | '/admin/users'
    | '/blog/$slug'
    | '/sell/assistant'
    | '/sell/orders'
    | '/sell/profile'
    | '/sell/promotions'
    | '/sell/settings'
    | '/shop/$slug'
    | '/store/$slug'
    | '/account/'
    | '/admin/'
    | '/sell/'
    | '/shop/'
    | '/account/orders/$id'
    | '/sell/products/$id'
    | '/sell/products/import'
    | '/sell/products/new'
    | '/sell/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SellRoute: typeof SellRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShopSlugRoute: typeof ShopSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof SellRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/settings': {
      id: '/sell/settings'
      path: '/settings'
      fullPath: '/sell/settings'
      preLoaderRoute: typeof SellSettingsRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/promotions': {
      id: '/sell/promotions'
      path: '/promotions'
      fullPath: '/sell/promotions'
      preLoaderRoute: typeof SellPromotionsRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/profile': {
      id: '/sell/profile'
      path: '/profile'
      fullPath: '/sell/profile'
      preLoaderRoute: typeof SellProfileRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/orders': {
      id: '/sell/orders'
      path: '/orders'
      fullPath: '/sell/orders'
      preLoaderRoute: typeof SellOrdersRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/assistant': {
      id: '/sell/assistant'
      path: '/assistant'
      fullPath: '/sell/assistant'
      preLoaderRoute: typeof SellAssistantRouteImport
      parentRoute: typeof SellRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/referrals': {
      id: '/account/referrals'
      path: '/referrals'
      fullPath: '/account/referrals'
      preLoaderRoute: typeof AccountReferralsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/sell/products/': {
      id: '/sell/products/'
      path: '/products'
      fullPath: '/sell/products/'
      preLoaderRoute: typeof SellProductsIndexRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/products/new': {
      id: '/sell/products/new'
      path: '/products/new'
      fullPath: '/sell/products/new'
      preLoaderRoute: typeof SellProductsNewRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/products/import': {
      id: '/sell/products/import'
      path: '/products/import'
      fullPath: '/sell/products/import'
      preLoaderRoute: typeof SellProductsImportRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/products/$id': {
      id: '/sell/products/$id'
      path: '/products/$id'
      fullPath: '/sell/products/$id'
      preLoaderRoute: typeof SellProductsIdRouteImport
      parentRoute: typeof SellRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountReferralsRoute: typeof AccountReferralsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountReferralsRoute: AccountReferralsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SellRouteChildren {
  SellAssistantRoute: typeof SellAssistantRoute
  SellOrdersRoute: typeof SellOrdersRoute
  SellProfileRoute: typeof SellProfileRoute
  SellPromotionsRoute: typeof SellPromotionsRoute
  SellSettingsRoute: typeof SellSettingsRoute
  SellIndexRoute: typeof SellIndexRoute
  SellProductsIdRoute: typeof SellProductsIdRoute
  SellProductsImportRoute: typeof SellProductsImportRoute
  SellProductsNewRoute: typeof SellProductsNewRoute
  SellProductsIndexRoute: typeof SellProductsIndexRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellAssistantRoute: SellAssistantRoute,
  SellOrdersRoute: SellOrdersRoute,
  SellProfileRoute: SellProfileRoute,
  SellPromotionsRoute: SellPromotionsRoute,
  SellSettingsRoute: SellSettingsRoute,
  SellIndexRoute: SellIndexRoute,
  SellProductsIdRoute: SellProductsIdRoute,
  SellProductsImportRoute: SellProductsImportRoute,
  SellProductsNewRoute: SellProductsNewRoute,
  SellProductsIndexRoute: SellProductsIndexRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SellRoute: SellRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShopSlugRoute: ShopSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
